### ISSUE TITLE
Fuel/electricity consumption units for stabilization and dewatering

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#107]
On both the _Crude Oil Stabilization_ and _Crude Oil Dewatering_ sheets, there are unit issues for the fuel consumption calculations. For the NG consumption there is an IF statement that would always lead it to show as kWh/d, though the units actually are always mmbtu/d. For the electricity consumption, eta_S_el and eta_heater_treater_electric have units of kWh/btu on the secondary inputs sheets. However, the calculation sheets treat it as if it is in kWh/mmbtu. To add to the confusion, looking at the default value, it seems like the unit actually represented (default=0.23) is probably MWh/mmbtu.

**Comment by smasnadi** [comment]
- Fixed! 
- divided cells N137 and N146 of Secondary Input sheet by 1000 to set the unit as kWh/btu

**Comment by smasnadi** [comment]
Adam: I fixed them, but as many unit conversion mistakes occurred I suggest you take a secondary look.

**Comment by qlangfitt** [comment]
@smasnadi  There is still an issue remaining - actually discovered this when fields with high GOR were suddenly not exporting any gas. On the _Crude Oil Stabilization_ sheet, Stabilizer column NG consumption (M48) was fine how it was before: =IF(Type_S="Gas",M47/Eta_S_fg,0). What I was asking to be changed was the cell next to it showing the units (N48). That cell is and was set up to show kWh/d, but the equation calculates in mmbtu/d. I was asking for the unit cell (N48) to be changed from kWh/d to mmbtu/d. Hopefully that makes sense.

The changes you made to the secondary inputs and to the stabilizer column electricity consumption look good to me.

**Comment by JSRuthe** [comment]
Fixed issue as recommended by Quinn above for crude oil stabilization. @arbrandt please take a look at unit conversions as pointed out my Mohammad

**Comment by arbrandt** [comment]
I cleaned these up as the unit conversions were complex. They are simpler now and all check out.
